DROP TABLE IF EXISTS SPORTS.TEAMS;

CREATE TABLE SPORTS.TEAMS
(
TEAM_ID INTEGER IDENTITY PRIMARY KEY,
SPORT_NAME VARCHAR(40) NULL,
LEAGUE_NAME VARCHAR(40) NULL,
TEAM_NAME VARCHAR(100) NULL,
TEAM_INAUGURAL_YEAR CHAR(4) NULL,
OTHER VARCHAR(20) NULL,
OTHER2 VARCHAR(20) NULL,
INSERTED_ON_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);