CREATE TABLE SPORTS.VENUE
(
VENUE_ID INTEGER IDENTITY PRIMARY KEY,
VENUE_NAME VARCHAR(100) NULL,
COUNTRY_CODE	 VARCHAR(100) NULL,
LANDMARK_CATEGORY VARCHAR(100) NULL,
LOCATION_LABEL VARCHAR(100) NULL,
FULL_ADDRESS	 VARCHAR(100) NULL,
MAP_CENTROID_LONGITUDE VARCHAR(100) NULL,	
MAP_CENTROID_LATITUDE VARCHAR(100) NULL,	
MAP_ACCURACY_CATAGORY VARCHAR(100) NULL,	
MAP_COORDINATE_SYSTEM_CATEGORY VARCHAR(100) NULL,	
IS_BOUNDARY_MAP_ON_FILE	 VARCHAR(100) NULL,
IS_SUBDIVISION_PARENT_SAME_AS_ENCLOSING_SUBDIVISION	 VARCHAR(100) NULL,
SUBDIVISION_PARENT_CODE_MUNICIPALITY  VARCHAR(100) NULL,	
PARENT_OF_MUNICIPALITY VARCHAR(100) NULL,
PARENT_SUBDIVISION_CATEGORY VARCHAR(100) NULL,
CAPACITY	 VARCHAR(100) NULL,
CAPACITY_METRIC_CATEGORY	 VARCHAR(100) NULL,
YEAR_OPENED	 VARCHAR(100) NULL,
VENTILATION_CATEGORY VARCHAR(100) NULL,
LANDMARK_NOTES  VARCHAR(100) NULL,
PHOTO_FILENAME VARCHAR(100) NULL,
IS_EMERGCENY_CONTRACT_RECORDED VARCHAR(100) NULL,

INSERTED_ON_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
 