/*
CREATE SCHEMA sports
AUTHORIZATION dbo
*/
IF OBJECT_ID ('sports.VENUE') IS NOT NULL
	TRUNCATE TABLE sports.VENUE;
GO
CREATE TABLE sports.VENUE
(
VENUE_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,

VENUE_NAME NVARCHAR(255) NULL,
COUNTRY_CODE NVARCHAR(255) NULL,
LANDMARK_CATEGORY NVARCHAR(255) NULL,
LOCATION_LABEL NVARCHAR(255) NULL,
FULL_ADDRESS NVARCHAR(255) NULL,
MAP_CENTROID_LONGITUDE NVARCHAR(255) NULL,	
MAP_CENTROID_LATITUDE NVARCHAR(255) NULL,	
MAP_ACCURACY_CATAGORY NVARCHAR(255) NULL,	
MAP_COORDINATE_SYSTEM_CATEGORY NVARCHAR(255) NULL,	
IS_BOUNDARY_MAP_ON_FILE NVARCHAR(255) NULL,
IS_SUBDIVISION_PARENT_SAME_AS_ENCLOSING_SUBDIVISION NVARCHAR(255) NULL,
SUBDIVISION_PARENT_CODE_MUNICIPALITY NVARCHAR(255) NULL,	
PARENT_OF_MUNICIPALITY NVARCHAR(255) NULL,
PARENT_SUBDIVISION_CATEGORY NVARCHAR(255) NULL,
CAPACITY  NVARCHAR(255) NULL,
CAPACITY_METRIC_CATEGORY NVARCHAR(255) NULL,
YEAR_OPENED	 NVARCHAR(255) NULL,
VENTILATION_CATEGORY NVARCHAR(255) NULL,
LANDMARK_NOTES  NVARCHAR(255) NULL,
PHOTO_FILENAME NVARCHAR(255) NULL,
IS_EMERGCENY_CONTRACT_RECORDED NVARCHAR(255) NULL,

INSERTED_ON_TIMESTAMP DATETIME2 CONSTRAINT DF_VENUE_INSERTED_ON DEFAULT (SYSUTCDATETIME())
);

GO
select 
	VENUE_NAME, 
	COUNTRY_CODE, 
	LANDMARK_CATEGORY, 
	LOCATION_LABEL, 
	FULL_ADDRESS, 
	MAP_CENTROID_LONGITUDE, 
	MAP_CENTROID_LATITUDE, 
	MAP_ACCURACY_CATAGORY, 
	MAP_COORDINATE_SYSTEM_CATEGORY, 
	IS_BOUNDARY_MAP_ON_FILE, 
	IS_SUBDIVISION_PARENT_SAME_AS_ENCLOSING_SUBDIVISION, 
	SUBDIVISION_PARENT_CODE_MUNICIPALITY, 
	PARENT_OF_MUNICIPALITY, 
	PARENT_SUBDIVISION_CATEGORY, 
	CAPACITY, 
	CAPACITY_METRIC_CATEGORY, 
	YEAR_OPENED, 
	VENTILATION_CATEGORY, 
	LANDMARK_NOTES, 
	PHOTO_FILENAME, 
	IS_EMERGCENY_CONTRACT_RECORDED 

from etl.sports.venue
